//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.TPCServiceSoap")]
    public interface TPCServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTree", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getTree(string projid, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTree", ReplyAction="*")]
        System.Threading.Tasks.Task getTreeAsync(string projid, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/publicGetTree", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void publicGetTree(string porj_id, string plan_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/publicGetTree", ReplyAction="*")]
        System.Threading.Tasks.Task publicGetTreeAsync(string porj_id, string plan_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getplan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getplan(string projid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getplan", ReplyAction="*")]
        System.Threading.Tasks.Task getplanAsync(string projid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getProgress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getProgress(string projid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getProgress", ReplyAction="*")]
        System.Threading.Tasks.Task getProgressAsync(string projid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/saveGuidAndProgress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void saveGuidAndProgress(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/saveGuidAndProgress", ReplyAction="*")]
        System.Threading.Tasks.Task saveGuidAndProgressAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPlanInfoByTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getPlanInfoByTime(System.DateTime startTime, System.DateTime endTime, string projID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPlanInfoByTime", ReplyAction="*")]
        System.Threading.Tasks.Task getPlanInfoByTimeAsync(System.DateTime startTime, System.DateTime endTime, string projID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/saveProgress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void saveProgress(string id, string progress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/saveProgress", ReplyAction="*")]
        System.Threading.Tasks.Task saveProgressAsync(string id, string progress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/savePlan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void savePlan(string projid, string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/savePlan", ReplyAction="*")]
        System.Threading.Tasks.Task savePlanAsync(string projid, string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/homePageProgress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void homePageProgress(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/homePageProgress", ReplyAction="*")]
        System.Threading.Tasks.Task homePageProgressAsync(string id);
        
        // CODEGEN: 消息 getprogressRequest 的包装名称(getprogress)以后生成的消息协定与默认值(getprogress1)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getprogress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MTService.ServiceReference1.getprogressResponse getprogress1(MTService.ServiceReference1.getprogressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getprogress", ReplyAction="*")]
        System.Threading.Tasks.Task<MTService.ServiceReference1.getprogressResponse> getprogress1Async(MTService.ServiceReference1.getprogressRequest request);
        
        // CODEGEN: 消息 saveprogressRequest 的包装名称(saveprogress)以后生成的消息协定与默认值(saveprogress1)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/saveprogress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MTService.ServiceReference1.saveprogressResponse saveprogress1(MTService.ServiceReference1.saveprogressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/saveprogress", ReplyAction="*")]
        System.Threading.Tasks.Task<MTService.ServiceReference1.saveprogressResponse> saveprogress1Async(MTService.ServiceReference1.saveprogressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertprogress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertprogress(string projid, string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertprogress", ReplyAction="*")]
        System.Threading.Tasks.Task insertprogressAsync(string projid, string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteprogress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void deleteprogress(string projid, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteprogress", ReplyAction="*")]
        System.Threading.Tasks.Task deleteprogressAsync(string projid, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/saveContent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void saveContent(string id, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/saveContent", ReplyAction="*")]
        System.Threading.Tasks.Task saveContentAsync(string id, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/saveNewPlan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void saveNewPlan(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/saveNewPlan", ReplyAction="*")]
        System.Threading.Tasks.Task saveNewPlanAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/saveCostList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void saveCostList(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/saveCostList", ReplyAction="*")]
        System.Threading.Tasks.Task saveCostListAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteCostList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void deleteCostList(string pid, string projId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteCostList", ReplyAction="*")]
        System.Threading.Tasks.Task deleteCostListAsync(string pid, string projId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCost", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getCost(string id, string projid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCost", ReplyAction="*")]
        System.Threading.Tasks.Task getCostAsync(string id, string projid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void updateTable(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateTable", ReplyAction="*")]
        System.Threading.Tasks.Task updateTableAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCostList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getCostList(string projid, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCostList", ReplyAction="*")]
        System.Threading.Tasks.Task getCostListAsync(string projid, string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getprogress", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getprogressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string proj;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime starttime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.DateTime endtime;
        
        public getprogressRequest() {
        }
        
        public getprogressRequest(string proj, System.DateTime starttime, System.DateTime endtime) {
            this.proj = proj;
            this.starttime = starttime;
            this.endtime = endtime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getprogressResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getprogressResponse {
        
        public getprogressResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveprogress", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class saveprogressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string proj;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string guid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string status;
        
        public saveprogressRequest() {
        }
        
        public saveprogressRequest(string proj, string guid, string status) {
            this.proj = proj;
            this.guid = guid;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveprogressResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class saveprogressResponse {
        
        public saveprogressResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TPCServiceSoapChannel : MTService.ServiceReference1.TPCServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TPCServiceSoapClient : System.ServiceModel.ClientBase<MTService.ServiceReference1.TPCServiceSoap>, MTService.ServiceReference1.TPCServiceSoap {
        
        public TPCServiceSoapClient() {
        }
        
        public TPCServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TPCServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TPCServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TPCServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void getTree(string projid, string type) {
            base.Channel.getTree(projid, type);
        }
        
        public System.Threading.Tasks.Task getTreeAsync(string projid, string type) {
            return base.Channel.getTreeAsync(projid, type);
        }
        
        public void publicGetTree(string porj_id, string plan_id) {
            base.Channel.publicGetTree(porj_id, plan_id);
        }
        
        public System.Threading.Tasks.Task publicGetTreeAsync(string porj_id, string plan_id) {
            return base.Channel.publicGetTreeAsync(porj_id, plan_id);
        }
        
        public void getplan(string projid) {
            base.Channel.getplan(projid);
        }
        
        public System.Threading.Tasks.Task getplanAsync(string projid) {
            return base.Channel.getplanAsync(projid);
        }
        
        public void getProgress(string projid) {
            base.Channel.getProgress(projid);
        }
        
        public System.Threading.Tasks.Task getProgressAsync(string projid) {
            return base.Channel.getProgressAsync(projid);
        }
        
        public void saveGuidAndProgress(string json) {
            base.Channel.saveGuidAndProgress(json);
        }
        
        public System.Threading.Tasks.Task saveGuidAndProgressAsync(string json) {
            return base.Channel.saveGuidAndProgressAsync(json);
        }
        
        public void getPlanInfoByTime(System.DateTime startTime, System.DateTime endTime, string projID) {
            base.Channel.getPlanInfoByTime(startTime, endTime, projID);
        }
        
        public System.Threading.Tasks.Task getPlanInfoByTimeAsync(System.DateTime startTime, System.DateTime endTime, string projID) {
            return base.Channel.getPlanInfoByTimeAsync(startTime, endTime, projID);
        }
        
        public void saveProgress(string id, string progress) {
            base.Channel.saveProgress(id, progress);
        }
        
        public System.Threading.Tasks.Task saveProgressAsync(string id, string progress) {
            return base.Channel.saveProgressAsync(id, progress);
        }
        
        public void savePlan(string projid, string json) {
            base.Channel.savePlan(projid, json);
        }
        
        public System.Threading.Tasks.Task savePlanAsync(string projid, string json) {
            return base.Channel.savePlanAsync(projid, json);
        }
        
        public void homePageProgress(string id) {
            base.Channel.homePageProgress(id);
        }
        
        public System.Threading.Tasks.Task homePageProgressAsync(string id) {
            return base.Channel.homePageProgressAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MTService.ServiceReference1.getprogressResponse MTService.ServiceReference1.TPCServiceSoap.getprogress1(MTService.ServiceReference1.getprogressRequest request) {
            return base.Channel.getprogress1(request);
        }
        
        public void getprogress1(string proj, System.DateTime starttime, System.DateTime endtime) {
            MTService.ServiceReference1.getprogressRequest inValue = new MTService.ServiceReference1.getprogressRequest();
            inValue.proj = proj;
            inValue.starttime = starttime;
            inValue.endtime = endtime;
            MTService.ServiceReference1.getprogressResponse retVal = ((MTService.ServiceReference1.TPCServiceSoap)(this)).getprogress1(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MTService.ServiceReference1.getprogressResponse> MTService.ServiceReference1.TPCServiceSoap.getprogress1Async(MTService.ServiceReference1.getprogressRequest request) {
            return base.Channel.getprogress1Async(request);
        }
        
        public System.Threading.Tasks.Task<MTService.ServiceReference1.getprogressResponse> getprogress1Async(string proj, System.DateTime starttime, System.DateTime endtime) {
            MTService.ServiceReference1.getprogressRequest inValue = new MTService.ServiceReference1.getprogressRequest();
            inValue.proj = proj;
            inValue.starttime = starttime;
            inValue.endtime = endtime;
            return ((MTService.ServiceReference1.TPCServiceSoap)(this)).getprogress1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MTService.ServiceReference1.saveprogressResponse MTService.ServiceReference1.TPCServiceSoap.saveprogress1(MTService.ServiceReference1.saveprogressRequest request) {
            return base.Channel.saveprogress1(request);
        }
        
        public void saveprogress1(string proj, string guid, string status) {
            MTService.ServiceReference1.saveprogressRequest inValue = new MTService.ServiceReference1.saveprogressRequest();
            inValue.proj = proj;
            inValue.guid = guid;
            inValue.status = status;
            MTService.ServiceReference1.saveprogressResponse retVal = ((MTService.ServiceReference1.TPCServiceSoap)(this)).saveprogress1(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MTService.ServiceReference1.saveprogressResponse> MTService.ServiceReference1.TPCServiceSoap.saveprogress1Async(MTService.ServiceReference1.saveprogressRequest request) {
            return base.Channel.saveprogress1Async(request);
        }
        
        public System.Threading.Tasks.Task<MTService.ServiceReference1.saveprogressResponse> saveprogress1Async(string proj, string guid, string status) {
            MTService.ServiceReference1.saveprogressRequest inValue = new MTService.ServiceReference1.saveprogressRequest();
            inValue.proj = proj;
            inValue.guid = guid;
            inValue.status = status;
            return ((MTService.ServiceReference1.TPCServiceSoap)(this)).saveprogress1Async(inValue);
        }
        
        public void insertprogress(string projid, string json) {
            base.Channel.insertprogress(projid, json);
        }
        
        public System.Threading.Tasks.Task insertprogressAsync(string projid, string json) {
            return base.Channel.insertprogressAsync(projid, json);
        }
        
        public void deleteprogress(string projid, string guid) {
            base.Channel.deleteprogress(projid, guid);
        }
        
        public System.Threading.Tasks.Task deleteprogressAsync(string projid, string guid) {
            return base.Channel.deleteprogressAsync(projid, guid);
        }
        
        public void saveContent(string id, string content) {
            base.Channel.saveContent(id, content);
        }
        
        public System.Threading.Tasks.Task saveContentAsync(string id, string content) {
            return base.Channel.saveContentAsync(id, content);
        }
        
        public void saveNewPlan(string id) {
            base.Channel.saveNewPlan(id);
        }
        
        public System.Threading.Tasks.Task saveNewPlanAsync(string id) {
            return base.Channel.saveNewPlanAsync(id);
        }
        
        public void saveCostList(string json) {
            base.Channel.saveCostList(json);
        }
        
        public System.Threading.Tasks.Task saveCostListAsync(string json) {
            return base.Channel.saveCostListAsync(json);
        }
        
        public void deleteCostList(string pid, string projId) {
            base.Channel.deleteCostList(pid, projId);
        }
        
        public System.Threading.Tasks.Task deleteCostListAsync(string pid, string projId) {
            return base.Channel.deleteCostListAsync(pid, projId);
        }
        
        public void getCost(string id, string projid) {
            base.Channel.getCost(id, projid);
        }
        
        public System.Threading.Tasks.Task getCostAsync(string id, string projid) {
            return base.Channel.getCostAsync(id, projid);
        }
        
        public void updateTable(string json) {
            base.Channel.updateTable(json);
        }
        
        public System.Threading.Tasks.Task updateTableAsync(string json) {
            return base.Channel.updateTableAsync(json);
        }
        
        public void getCostList(string projid, string id) {
            base.Channel.getCostList(projid, id);
        }
        
        public System.Threading.Tasks.Task getCostListAsync(string projid, string id) {
            return base.Channel.getCostListAsync(projid, id);
        }
    }
}
